# -*- coding: utf-8 -*-
"""akbarnih.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCzU1m0y2mDSeAdzwi3akTVbPNpzXrYj
"""

nama = 'akbar moy'
asal = 'marvel cinematic universe'

print(nama)

print(nama+asal)

print('halo','nama saya', nama )

print('halo','nama saya', nama,'asal saya', asal)

data_lengkap = nama, asal

print(data_lengkap)

asal = 'marvel cinematic universe'
kode_pos = 7783

asal_kode_pos = asal, kode_pos

print(asal_kode_pos)

