# -*- coding: utf-8 -*-
"""run boy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUTlzKu4v1nqWHwsNUb0ZK2-Ynh5qstC
"""

print('dia berkata : pergilah')

print(" aku menimpali: \"apakah kau ingin 'angkat kaki'?!\" ")

print(" \\(^_^)/(\\-_-) ")

