# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCzU1m0y2mDSeAdzwi3akTVbPNpzXrYj
"""

nama = 'akbar moy'
asal = 'mcu'

print(nama)

print(nama+asal)

print('halo','nama saya', nama )

print('halo','nama saya', nama,'asal saya', asal)

data_lengkap = nama, asal

print(data_lengkap)

